apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
spec: # DeploymentSpec - Specification of the desired behavior of the Deployment.
  selector: #Label selector for pods. Existing ReplicaSets whose pods are selected by this 
            # will be the ones affected by this deployment.
    matchLabels:
      app: sample-html
  replicas: 2
  template: # PodTemplateSpec- Template describes the pods that will be created.
    metadata:
      labels:
        app: sample-html
    spec: # PodSpec - Specification of the desired behavior of the pod. 
      containers:  # List of containers belonging to the pod. 
      - name: sample-html
        image: isingh14/sample-html:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  type: NodePort
  ports:
  - nodePort: 30500
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: sample-html


